CREATE TABLE [dbo].[WordsStatistic](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[word] [varchar](max) NOT NULL,
	[count] [int] NULL,
 CONSTRAINT [PK_WordsStatistic] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
